version: "3.3"
services:
  funnels_nginx:
    build: ./funnels
    networks:
      - backend
    ports:
      - 80:80
    restart: always
    env_file:
      - .env
  funnelws:
    build: ./ws
    networks:
      - backend
    ports:
      - 4000:3000
    environment:
      NODE_ENV: development
networks:
  backend: