version: "3.3"
services:
  funnels_nginx:
    build: ./funnels
    networks:
      - backend
    ports:
      - 80:80
    restart: always
    env_file:
      - .env
    depends_on:
      - platform-proxy
  funnelws:
    build: ./ws
    networks:
      - backend
    ports:
      - 4000:3000
    environment:
      NODE_ENV: development
  platform-proxy:
    build: ./platform-proxy
    command: npm run start:prod
    networks:
      - backend
    ports:
      - 3005:3005
    environment:
      NODE_ENV: production
networks:
  backend: